name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  shellcheck_scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/shellcheck.sh

  # These are all broken out so they run in parallel
  test_alpine_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./scripts/test_install_on_alpine.sh

  test_debian_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./scripts/test_install_on_debian.sh

  test_ubuntu_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./scripts/test_install_on_ubuntu.sh

  test_fedora_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./scripts/test_install_on_fedora.sh

  test_rhel_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./scripts/test_install_on_rhelubi.sh

  test_amazonlinux_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./scripts/test_install_on_amazonlinux.sh
